### PR TITLE
BUG Display a notification after publishing a campaign

### LINKED ISSUE #131: User should receive a toast confirmation when publishing a campaign
When a campaign is published there is no feedback for the user to confirm that their publishing action was successful.

A toast message like 'Published "[Campaign name]" successfully.' should be used

### ACs
- Finalise existing PR
- Test and confirm functionality with PUX

## PR
- https://github.com/silverstripe/silverstripe-campaign-admin/pull/177

### PR DESCRIPTION
**Pull request by maxime-rainville**
Use the new react toast notification to tell the user when their campaign has been published.

# Parent issue
* resolves #131 

# Depends on
* https://github.com/silverstripe/silverstripe-admin/pull/1068
* https://github.com/silverstripe/silverstripe-framework/pull/9770

### CODE REVIEW

**Comment by maxime-rainville** [comment]
Might need to wrtie some unit test and behat test + bump dependencies.

File: client/src/state/campaign/CampaignActions.js [hunk 1]
```diff
@@ -64,12 +66,22 @@ export function publishCampaign(publishApi, recordType, campaignId) {
           type: RECORD_ACTION_TYPES.FETCH_RECORD_SUCCESS,
           payload: { recordType, data },
         });
+        const message = i18n._t(
+          'CampaignAdmin.PUBLISH_SUCCESS',
+          '"%s" campaign has been published.'
```
Comment (sachajudd) [inline client/src/state/campaign/CampaignActions.js:71]: We need to ensure we are using the same patterns in the CMS, can we check what pages do? As this is not the same wording that was recommended by Jared.

File: client/lang/src/en.json [hunk 2]
```diff
@@ -8,5 +8,7 @@
     "CampaignAdmin.NO_CHANGES": "No changes",
     "CampaignAdmin.PUBLISHCAMPAIGN": "Publish campaign",
     "CampaignAdmin.REMOVED": "Removed",
-    "CampaignAdmin.REVERTCAMPAIGN": "Revert"
-}
\ No newline at end of file
+    "CampaignAdmin.REVERTCAMPAIGN": "Revert",
+    "CampaignAdmin.PUBLISH_FAIL": "Campaign could not be published.",
+    "CampaignAdmin.PUBLISH_SUCCESS": "\"%s\" campaign has been published."
```
Comment (bergice) [inline client/lang/src/en.json:13]:
```suggestion
    "CampaignAdmin.PUBLISH_SUCCESS": "Published \"%s\" successfully."
```

File: client/src/state/campaign/CampaignActions.js (hunk 1 above)
Comment (bergice) [inline client/src/state/campaign/CampaignActions.js:71]:
```suggestion
          'Published "%s" successfully.'
```

**Review by bergice — CHANGES_REQUESTED** [review]

**Comment by bergice** [comment]
Seems to work, just need to update the text and fix travis.

**Comment by maxime-rainville** [comment]
Updated the messages and added some behat test. The behat test won't be green until the matching framework PR is merged.

File: client/src/state/campaign/CampaignActions.js (hunk 1 above)
Comment (maxime-rainville) [reply client/src/state/campaign/CampaignActions.js]: Translation is now `Published \"%s\" successfully.` which is the same message used when publishing a page.

File: client/lang/src/en.json [hunk 3]
```diff
@@ -8,5 +8,7 @@
     "CampaignAdmin.NO_CHANGES": "No changes",
     "CampaignAdmin.PUBLISHCAMPAIGN": "Publish campaign",
     "CampaignAdmin.REMOVED": "Removed",
-    "CampaignAdmin.REVERTCAMPAIGN": "Revert"
-}
\ No newline at end of file
+    "CampaignAdmin.REVERTCAMPAIGN": "Revert",
+    "CampaignAdmin.PUBLISH_FAIL": "Campaign could not be published.",
```
Comment (sachajudd) [inline client/lang/src/en.json:12]: @maxime-rainville What does a page do when it fails publishing?

File: client/lang/src/en.json [hunk 4]
```diff
@@ -8,5 +8,7 @@
     "CampaignAdmin.NO_CHANGES": "No changes",
     "CampaignAdmin.PUBLISHCAMPAIGN": "Publish campaign",
     "CampaignAdmin.REMOVED": "Removed",
-    "CampaignAdmin.REVERTCAMPAIGN": "Revert"
-}
\ No newline at end of file
+    "CampaignAdmin.REVERTCAMPAIGN": "Revert",
```
Comment (sachajudd) [inline client/lang/src/en.json:11]: Something like: Reverted \"%s\" could give more context as to what is being reverted?

Comment (maxime-rainville) [reply client/lang/src/en.json:11]: As far as I know, that feature hasn't been implemented.

File: client/lang/src/en.json (hunk 3 above)
Comment (maxime-rainville) [reply client/lang/src/en.json:12]: The expectation here is that the back end will give us a proper error message and we will display that.

This string is only here in case we don't get an error message back and we don't know why publication failed.

**Review by sachajudd — APPROVED** [review]
Approved from UX perspective.

**Review by emteknetnz — CHANGES_REQUESTED** [review]
Code looks fine and tests fine

It might be worth creating another issue for making a toast notification for when you inline CREATE a campaign 

image

You've got a behat timeout on travis that'll need to be fixed

**Comment by maxime-rainville** [comment]
Just had a glance to see if we could sneak in a "successfully added" toast notification is this PR. Sadly, it looks non-trivial. 

The add to campaign logic is actually in admin for some weird reason. https://github.com/silverstripe/silverstripe-admin/blob/1/client/src/legacy/AddToCampaignForm.js

**Comment by maxime-rainville** [comment]
Added a follow up issue for "the add to campaign" modal https://github.com/silverstripe/silverstripe-campaign-admin/issues/190
