### PR TITLE
MINOR Fix close and help button appearance

### LINKED ISSUE #86: Help icon is not centered horizontally
Add the class .btn--no-text to the button so that it removes the space which typically sits between the icon and text.

image

### PR DESCRIPTION
**Pull request by lukereative**
Fixes #86

### CODE REVIEW

File: client/src/components/IntroScreen/IntroScreen.js [hunk 1]
```diff
@@ -50,7 +50,7 @@ class IntroScreen extends Component {
     return (
       <div className="fill-width campaign-info">
         <div className="campaign-info__icon">
-          <span className="font-icon-white-question icon btn--icon-xl" />
+          <span className="font-icon-white-question icon btn--icon-xl btn--no-text" />
```
Comment (maxime-rainville) [inline client/src/components/IntroScreen/IntroScreen.js]: We should have an aria label on this.

File: client/src/containers/CampaignAdmin/CampaignAdmin.js [hunk 2]
```diff
@@ -416,7 +416,7 @@ By removing this item all linked items will be removed unless used elsewhere.`;
                   role="button"
                   tabIndex={0}
                   onClick={this.handleToggleMessage}
-                  className="btn btn-secondary font-icon-white-question btn--icon-xl"
+                  className="btn btn-secondary font-icon-white-question btn--icon-xl btn--no-text"
```
Comment (maxime-rainville) [inline client/src/containers/CampaignAdmin/CampaignAdmin.js]: We should have an aria label on this.
